test('My 1st test case!', () => {

})

test('Failing test case', () => {
	throw new Error('Failure!')
})